/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.professor;

import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ProfessorDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;
    /**
     * Creates new form ProfessorDashboardPanel
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     */
    public ProfessorDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj) {
        initComponents();
        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        profMenuPanel = new javax.swing.JPanel();
        profCourseCatlogButton = new javax.swing.JButton();
        profRegisterCourseButton = new javax.swing.JButton();
        profManageCourseButton = new javax.swing.JButton();
        profTeachingHistoryButton = new javax.swing.JButton();
        profViewStudentsButton = new javax.swing.JButton();
        profProfileButton = new javax.swing.JButton();
        profContentPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        profMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        profCourseCatlogButton.setBackground(new java.awt.Color(51, 153, 255));
        profCourseCatlogButton.setText("Course Catalog");
        profCourseCatlogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profCourseCatlogButtonActionPerformed(evt);
            }
        });

        profRegisterCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        profRegisterCourseButton.setText("Register Course");

        profManageCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        profManageCourseButton.setText("Manage Course");

        profTeachingHistoryButton.setBackground(new java.awt.Color(51, 153, 255));
        profTeachingHistoryButton.setText("Teaching History");

        profViewStudentsButton.setBackground(new java.awt.Color(51, 153, 255));
        profViewStudentsButton.setText("View Students");

        profProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        profProfileButton.setText("Profile");
        profProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profMenuPanelLayout = new javax.swing.GroupLayout(profMenuPanel);
        profMenuPanel.setLayout(profMenuPanelLayout);
        profMenuPanelLayout.setHorizontalGroup(
            profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profCourseCatlogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profRegisterCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profManageCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profTeachingHistoryButton)
                .addGap(18, 18, 18)
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profViewStudentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        profMenuPanelLayout.setVerticalGroup(
            profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profMenuPanelLayout.createSequentialGroup()
                .addComponent(profProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profCourseCatlogButton)
                    .addComponent(profRegisterCourseButton)
                    .addComponent(profManageCourseButton)
                    .addComponent(profTeachingHistoryButton)
                    .addComponent(profViewStudentsButton))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(profMenuPanel);

        profContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        profContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(profContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profCourseCatlogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profCourseCatlogButtonActionPerformed
        // TODO add your handling code here:
        ProfCourseCatalogPanel courseCatalog = new ProfCourseCatalogPanel(profContentPanel);
        profContentPanel.add("ProfCourseCatalog", courseCatalog);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profCourseCatlogButtonActionPerformed

    private void profProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profProfileButtonActionPerformed
        // TODO add your handling code here:
        ProfessorProfileResetPanel profProfileReset = new ProfessorProfileResetPanel(
                appContainerPanel, profContentPanel, userObj, userSignUpObj);
        profContentPanel.add("ProfProfileReset", profProfileReset);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel profContentPanel;
    private javax.swing.JButton profCourseCatlogButton;
    private javax.swing.JButton profManageCourseButton;
    private javax.swing.JPanel profMenuPanel;
    private javax.swing.JButton profProfileButton;
    private javax.swing.JButton profRegisterCourseButton;
    private javax.swing.JButton profTeachingHistoryButton;
    private javax.swing.JButton profViewStudentsButton;
    // End of variables declaration//GEN-END:variables
}
