/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.student;

import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class StudentDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;

    /**
     * Creates new form StudentDashboardPanel
     *
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     */
    public StudentDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj) {
        initComponents();
        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        studentMenuPanel = new javax.swing.JPanel();
        studentProfileButton = new javax.swing.JButton();
        CourseCatalogButton = new javax.swing.JButton();
        RegisterCourseButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        studentContentPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        studentMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        studentProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        studentProfileButton.setText("Profile");
        studentProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentProfileButtonActionPerformed(evt);
            }
        });

        CourseCatalogButton.setBackground(new java.awt.Color(51, 153, 255));
        CourseCatalogButton.setText("Course Catalog");

        RegisterCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        RegisterCourseButton.setText("Register Course");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Transcript");

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setText("Certification Request");

        javax.swing.GroupLayout studentMenuPanelLayout = new javax.swing.GroupLayout(studentMenuPanel);
        studentMenuPanel.setLayout(studentMenuPanelLayout);
        studentMenuPanelLayout.setHorizontalGroup(
            studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(studentProfileButton)
                .addContainerGap())
            .addGroup(studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CourseCatalogButton)
                .addGap(18, 18, 18)
                .addComponent(RegisterCourseButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentMenuPanelLayout.setVerticalGroup(
            studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseCatalogButton)
                    .addComponent(RegisterCourseButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(studentMenuPanel);

        studentContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(studentContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentProfileButtonActionPerformed
        // TODO add your handling code here:
        StudentProfileResetPanel studentProfile = new StudentProfileResetPanel(
                appContainerPanel, studentContentPanel, userObj, userSignUpObj);
        studentContentPanel.add("StudentProfileReset", studentProfile);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_studentProfileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CourseCatalogButton;
    private javax.swing.JButton RegisterCourseButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel studentContentPanel;
    private javax.swing.JPanel studentMenuPanel;
    private javax.swing.JButton studentProfileButton;
    // End of variables declaration//GEN-END:variables
}
